name: sebschat-server-stack
services:
  sebschat-server:
    container_name: sebschat-server
    hostname: sebschat-server
    build: .
    image: sebschat-server
    depends_on:
      - sebschat-mongodb
    ports:
      - "3000:3000"
    environment:
    - "MONGODB_CONNECTION_STRING=mongodb://sebschat-mongodb:27017/sebschat"
    - "SERVER_PORT=3000"
  sebschat-mongodb:
    image: mongo:noble
    container_name: sebschat-mongodb
    ports:
      - "27017:27017"